### ISSUE TITLE
[버그 해결] 스프링시큐리티 적용 후 컴파일 문제 해결

### ISSUE THREAD

**Issue by manijang2** [haedal-uni/dangdang#75]
컴파일 후 일부 필드를 못읽는 문제가 발생하여 버그를 해결하고자 합니다

![스크린샷 2021-12-10 오전 2 55 45](https://user-images.githubusercontent.com/29498316/145450011-d3316af9-7336-4c78-baac-9aa9e1478587.png)

**Comment by great-psycho** [comment]
저도 에러가 있어서 지금 제 코드가 문제인가 알아보고있습니다.

**Comment by manijang2** [comment]
완료되어 이슈를 닫습니다.
